server:
  port: 8001
spring:
  application:
    name: interview
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.116.218.222:3306/db_sheng_an_de?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: user_three
    password: 123456
  data:
    redis:
      host: 47.116.218.222
      port: 6379
      database: 0
      password: xuan-123
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
#        cluster:
#          refresh:
#            adaptive: true # 支持集群拓扑动态感知刷新，自适应拓扑刷新是否使用所有可用的更新，默认false关闭
#            period: 2000 # 定时刷新
#     cluster: # 集群配置相关
#       nodes: # 集群节点



# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yangjian.entities
  configuration:
    map-underscore-to-camel-case: true

# =======================mysql pagehelper ============================
pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true
